name: Quadratic Equation Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.0-rc.1'
      - name: Setup Coverage
        run: |
          pip install genbadge[coverage]
          pip install coverage
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov coveralls
          coverage run -m pytest test_myfile.py
          coveralls --service=github-actions
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
